# Generated by Django 4.1.4 on 2022-12-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whyImg', models.ImageField(upload_to='why_choose_us_img')),
                ('whyName', models.CharField(max_length=250)),
                ('whyDes', models.TextField()),
            ],
        ),
    ]
