# Generated by Django 4.1.4 on 2022-12-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetTheTeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberImg', models.ImageField(upload_to='meet_the_team_members_img')),
                ('memberName', models.CharField(max_length=250)),
                ('memberDes', models.TextField()),
            ],
        ),
    ]
